[package]
name = "store"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
sqlx.workspace = true
tracing.workspace = true
time.workspace = true
jvdata-core = { version = "0.1.0", path = "../jvdata-core" }
sha2.workspace = true

[dev-dependencies]
tokio.workspace = true
bridge = { version = "0.1.0", path = "../bridge" }

[lints]
workspace = true
